# Site settings
title: Podcast recommendations from @davidpots
email: davidpots@gmail.com
description: A curated mixtape of recommended podcast episodes. Maintained by David Potsiadlo.
baseurl: "/podcasts/" # the subpath of your site, e.g. /blog/
url: "http://www.davidpots.com/podcasts" # the base hostname & protocol for your site
twitter_username: davidpots
github_username:  davidpots
thumbnail: "http://davidpots.com/podcasts/images/feed-background-v5.jpg"

# Build settings
markdown: kramdown

collections:
  podcasts:
    output: true
  episodes:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "podcasts" # a collection in your site, in plural form
    values:
      layout: "podcast"
  -
    scope:
      path: ""
      type: "episodes" # a collection in your site, in plural form
    values:
      layout: "episode"
